name: Keyword Checks

on:
  push:
  schedule:
  - cron: "46 0-4 2      * *" # early morning hours on a 2nd day of the month
  - cron: "46 13  1,3-31 * *" # 13:46 on all other days
  workflow_dispatch:
    inputs:
      date:
        description: date
        required: false
        
jobs:
  prep:
    runs-on: ubuntu-latest
    container: gentoo/stage3

    steps:
    - name: get date
      run: (test "$DATE" && echo "NEWDATE=$DATE" || echo NEWDATE=$(date --date="1 day ago" +%Y%m%d)) | tee -a $GITHUB_ENV
      env:
        DATE: ${{ inputs.date }}

    - name: cache getuto keys
      uses: actions/cache@v4
      with:
        key: getuto-${{ env.NEWDATE }}
        path: /etc/portage/gnupg
        restore-keys: getuto-

    - name: cache whole tree
      id: cache-tree
      uses: actions/cache@v4
      with:
        key: portage-${{ env.NEWDATE }}
        path: /var/db/repos/gentoo

    - name: cache tree snapshot
      id: cache-snapshot
      uses: actions/cache@v4
      with:
        key: distfiles-${{ env.NEWDATE }}
        path: /var/cache/distfiles
        restore-keys: distfiles-

    - name: get portage tree
      if: ${{ steps.cache-tree.outputs.cache-hit != 'true' }}
      run: emerge-webrsync --quiet ${NEWDATE:+--revert=$NEWDATE}

    - name: install git
      run: |
        echo ::group::getuto
        getuto
        echo ::endgroup::
        echo ::group::install git
        emerge --update --quiet --getbinpkg dev-vcs/git
        echo ::endgroup::

    outputs:
      date: ${{ env.NEWDATE }}

  trigger:
    uses: ./.github/workflows/reuse.yml
    needs: prep
    strategy:
      matrix:
        package:
        - kde-frameworks/kirigami
        - sys-apps/systemd
        - app-crypt/libb2
        - net-libs/gnutls
    with:
      date: ${{ needs.prep.outputs.date }}
      package: ${{ matrix.package }}
